(in-package :su-real)

;; @author Luca Krohm
(def-fact-group suturo-action (desig:action-grounding)
  ;; @author Luca Krohm
  (<- (action-grounding ?designator (su-real:pick-up ?resolved-action-designator))
    (spec:property ?designator (:type :picking-up))
    (once (or (desig:desig-prop ?designator (:collision-mode ?collision-mode))
              (equal ?collision-mode nil)))
    (once (or (desig:desig-prop ?designator (:collision-object-b ?collision-object-b))
              (equal ?collision-object-b nil)))
    (once (or (desig:desig-prop ?designator (:collision-object-b-link
                                             ?collision-object-b-link))
              (equal ?collision-object-b-link nil)))
    (once (or (desig:desig-prop ?designator (:collision-object-a ?collision-object-a))
              (equal ?collision-object-a nil)))
    (once (or (desig:desig-prop ?designator (:move-base ?move-base))
              (equal ?move-base nil)))
    (once (or (desig:desig-prop ?designator (:prefer-base ?prefer-base))
              (equal ?prefer-base nil)))
    (once (or (desig:desig-prop ?designator (:straight-line ?straight-line))
              (equal ?straight-line nil)))
    (once (or (desig:desig-prop ?designator (:align-planes-left ?align-planes-left))
              (equal ?align-planes-left nil)))
    (once (or (desig:desig-prop ?designator (:align-planes-right ?align-planes-right))
              (equal ?align-planes-right nil)))
    (once (or (desig:desig-prop ?designator (:precise-tracking ?precise-tracking))
              (equal ?precise-tracking nil)))
    (once (or (desig:desig-prop ?designator (:object-type ?object-type))
              (equal ?object-type nil)))
    (once (or (desig:desig-prop ?designator (:goal-pose ?goal-pose))
              (equal ?goal-pose nil)))
    (once (or (desig:desig-prop ?designator (:object-size ?object-size))
              (equal ?object-size nil)))
    (once (or (desig:desig-prop ?designator (:object-shape ?object-shape))
              (equal ?object-shape nil)))
    (once (or (desig:desig-prop ?designator (:object-name ?object-name))
              (equal ?object-name nil)))
    (once (or (desig:desig-prop ?designator (:from-above ?from-above))
              (equal ?from-above nil)))
    (once (or (desig:desig-prop ?designator (:sequence-goal ?sequence-goal))
              (equal ?sequence-goal nil)))

    (desig:designator :action ((:type :picking-up)
                               (:collision-mode ?collision-mode)
                               (:collision-object-b ?collision-object-b)
                               (:collision-object-b-link ?collision-object-b-link)
                               (:collision-object-a ?collision-object-a)
                               (:move-base ?move-base)
                               (:prefer-base ?prefer-base)
                               (:align-planes-left ?align-planes-left)
                               (:align-planes-right ?align-planes-right)
                               (:straight-line ?straight-line)
                               (:precise-tracking ?precise-tracking)
                               (:object-type ?object-type)
                               (:goal-pose ?goal-pose)
                               (:object-size ?object-size)
                               (:object-shape ?object-shape)
                               (:object-name ?object-name)
                               (:from-above ?from-above)
                               (:sequence-goal ?sequence-goal)
                               )
                      ?resolved-action-designator))

  ;; @author Luca Krohm
  (<- (action-grounding ?designator (su-real:place ?resolved-action-designator))
    (spec:property ?designator (:type :placing))
    (once (or (desig:desig-prop ?designator (:collision-mode ?collision-mode))
              (equal ?collision-mode nil)))
    (once (or (desig:desig-prop ?designator (:collision-object-b ?collision-object-b))
              (equal ?collision-object-b nil)))
    (once (or (desig:desig-prop ?designator (:collision-object-b-link
                                             ?collision-object-b-link))
              (equal ?collision-object-b-link nil)))
    (once (or (desig:desig-prop ?designator (:collision-object-a ?collision-object-a))
              (equal ?collision-object-a nil)))
    (once (or (desig:desig-prop ?designator (:move-base ?move-base))
              (equal ?move-base nil)))
    (once (or (desig:desig-prop ?designator (:prefer-base ?prefer-base))
              (equal ?prefer-base nil)))
    (once (or (desig:desig-prop ?designator (:straight-line ?straight-line))
              (equal ?straight-line nil)))
    (once (or (desig:desig-prop ?designator (:align-planes-left ?align-planes-left))
              (equal ?align-planes-left nil)))
    (once (or (desig:desig-prop ?designator (:align-planes-right ?align-planes-right))
              (equal ?align-planes-right nil)))
    (once (or (desig:desig-prop ?designator (:precise-tracking ?precise-tracking))
              (equal ?precise-tracking nil)))
    (once (or (desig:desig-prop ?designator (:goal-pose ?goal-pose))
              (equal ?goal-pose nil)))
    (once (or (desig:desig-prop ?designator (:object-size ?object-size))
              (equal ?object-size nil)))
    (once (or (desig:desig-prop ?designator (:from-above ?from-above))
              (equal ?from-above nil)))
    (once (or (desig:desig-prop ?designator (:neatly ?neatly))
              (equal ?neatly nil)))

    (desig:designator :action ((:type :placing)
                               (:collision-mode ?collision-mode)
                               (:collision-object-b ?collision-object-b)
                               (:collision-object-b-link ?collision-object-b-link)
                               (:collision-object-a ?collision-object-a)
                               (:move-base ?move-base)
                               (:prefer-base ?prefer-base)
                               (:align-planes-left ?align-planes-left)
                               (:align-planes-right ?align-planes-right)
                               (:straight-line ?straight-line)
                               (:precise-tracking ?precise-tracking)
                               (:goal-pose ?goal-pose)
                               (:object-size ?object-size)
                               (:from-above ?from-above)
                               (:neatly ?neatly))
                      ?resolved-action-designator))

   ;; @author Luca Krohm
  (<- (action-grounding ?designator (su-real:open-door ?resolved-action-designator))
    (spec:property ?designator (:type :opening-door))
    (once (or (desig:desig-prop ?designator (:collision-mode ?collision-mode))
              (equal ?collision-mode nil)))
    (once (or (desig:desig-prop ?designator (:collision-object-b ?collision-object-b))
              (equal ?collision-object-b nil)))
    (once (or (desig:desig-prop ?designator (:collision-object-b-link
                                             ?collision-object-b-link))
              (equal ?collision-object-b-link nil)))
    (once (or (desig:desig-prop ?designator (:collision-object-a ?collision-object-a))
              (equal ?collision-object-a nil)))
    (once (or (desig:desig-prop ?designator (:move-base ?move-base))
              (equal ?move-base nil)))
    (once (or (desig:desig-prop ?designator (:prefer-base ?prefer-base))
              (equal ?prefer-base nil)))
    (once (or (desig:desig-prop ?designator (:straight-line ?straight-line))
              (equal ?straight-line nil)))
    (once (or (desig:desig-prop ?designator (:align-planes-left ?align-planes-left))
              (equal ?align-planes-left nil)))
    (once (or (desig:desig-prop ?designator (:align-planes-right ?align-planes-right))
              (equal ?align-planes-right nil)))
    (once (or (desig:desig-prop ?designator (:precise-tracking ?precise-tracking))
              (equal ?precise-tracking nil)))
    (once (or (desig:desig-prop ?designator (:handle-link ?handle-link))
              (equal ?handle-link nil)))
    (once (or (desig:desig-prop ?designator (:joint-angle ?joint-angle))
              (equal ?joint-angle nil)))

    (desig:designator :action ((:type :opening-door)
                               (:collision-mode ?collision-mode)
                               (:collision-object-b ?collision-object-b)
                               (:collision-object-b-link ?collision-object-b-link)
                               (:collision-object-a ?collision-object-a)
                               (:move-base ?move-base)
                               (:prefer-base ?prefer-base)
                               (:align-planes-left ?align-planes-left)
                               (:align-planes-right ?align-planes-right)
                               (:straight-line ?straight-line)
                               (:precise-tracking ?precise-tracking)
                               (:handle-link ?handle-link)
                               (:joint-angle ?joint-angle))
                      ?resolved-action-designator))

  ;; @author Luca Krohm
  (<- (action-grounding ?designator (su-real:su-pour ?resolved-action-designator))
    (spec:property ?designator (:type :su-pouring))
    (once (or (desig:desig-prop ?designator (:collision-mode ?collision-mode))
              (equal ?collision-mode nil)))
    (once (or (desig:desig-prop ?designator (:collision-object-b ?collision-object-b))
              (equal ?collision-object-b nil)))
    (once (or (desig:desig-prop ?designator (:collision-object-b-link
                                             ?collision-object-b-link))
              (equal ?collision-object-b-link nil)))
    (once (or (desig:desig-prop ?designator (:collision-object-a ?collision-object-a))
              (equal ?collision-object-a nil)))
    (once (or (desig:desig-prop ?designator (:object-size ?object-size))
              (equal ?object-size nil)))
    (once (or (desig:desig-prop ?designator (:target-object ?target-object))
              (equal ?target-object nil)))
    (once (or (desig:desig-prop ?designator (:target-size ?target-size))
              (equal ?target-size nil)))
    (once (or (desig:desig-prop ?designator (:target-name ?target-name))
              (equal ?target-name nil)))

    (desig:designator :action ((:type :su-pouring)
                               (:collision-mode ?collision-mode)
                               (:collision-object-b ?collision-object-b)
                               (:collision-object-b-link ?collision-object-b-link)
                               (:collision-object-a ?collision-object-a)
                               (:object-size ?object-size)
                               (:target-object ?target-object)
                               (:target-size ?target-size)
                               (:target-name ?target-name))
                      ?resolved-action-designator))


  (<- (action-grounding ?designator (su-real:sequence ?resolved-action-designator))
    (spec:property ?designator (:type :sequence-goal))
    (once (or (desig:desig-prop ?designator (:action ?action))
              (equal ?action nil)))
    (once (or (desig:desig-prop ?designator (:motions ?motions))
              (equal ?motions nil)))
    (once (or (desig:desig-prop ?designator (:collision-mode ?collision-mode))
              (equal ?collision-mode nil)))
    (once (or (desig:desig-prop ?designator (:object-type ?object-type))
              (equal ?object-type nil)))
    (once (or (desig:desig-prop ?designator (:goal-pose ?goal-pose))
              (equal ?goal-pose nil)))
    (once (or (desig:desig-prop ?designator (:object-height ?object-height))
              (equal ?object-height nil)))
    (once (or (desig:desig-prop ?designator (:object-size ?object-size))
              (equal ?object-size nil)))
    (once (or (desig:desig-prop ?designator (:object-shape ?object-shape))
              (equal ?object-shape nil)))
    (once (or (desig:desig-prop ?designator (:object-name ?object-name))
              (equal ?object-name nil)))
    (once (or (desig:desig-prop ?designator (:from-above ?from-above))
              (equal ?from-above nil)))
    (once (or (desig:desig-prop ?designator (:target-object ?target-object))
              (equal ?target-object nil)))
    (once (or (desig:desig-prop ?designator (:target-size ?target-size))
              (equal ?target-size nil)))
    (once (or (desig:desig-prop ?designator (:target-name ?target-name))
              (equal ?target-name nil)))
    (once (or (desig:desig-prop ?designator (:tilt-angle ?tilt-angle))
              (equal ?tilt-angle nil)))
    (once (or (desig:desig-prop ?designator (:reference-frame ?reference-frame))
              (equal ?reference-frame nil)))

    (desig:designator :action ((:type :sequence-goal)
                               (:action ?action)
                               (:motions ?motions)
                               (:collision-mode ?collision-mode)
                               (:object-type ?object-type)
                               (:goal-pose ?goal-pose)
                               (:object-height ?object-height)
                               (:object-size ?object-size)
                               (:object-shape ?object-shape)
                               (:object-name ?object-name)
                               (:from-above ?from-above)
                               (:target-object ?target-object)
                               (:target-size ?target-size)
                               (:target-name ?target-name)
                               (:tilt-angle ?tilt-angle)
                               (:reference-frame ?reference-frame)
                               )
                      ?resolved-action-designator))

  (<- (action-grounding ?designator (su-real:take-pose ?resolved-action-designator))
    (spec:property ?designator (:type :taking-pose))
    (once (or (desig:desig-prop ?designator (:pose-keyword ?pose-keyword))
              (equal ?pose-keyword nil)))
    (once (or (desig:desig-prop ?designator (:head-pan ?head-pan))
              (equal ?head-pan nil)))
    (once (or (desig:desig-prop ?designator (:head-tilt ?head-tilt))
              (equal ?head-tilt nil)))
    (once (or (desig:desig-prop ?designator (:arm-lift ?arm-lift))
              (equal ?arm-lift nil)))
    (once (or (desig:desig-prop ?designator (:arm-flex ?arm-flex))
              (equal ?arm-flex nil)))
    (once (or (desig:desig-prop ?designator (:arm-roll ?arm-roll))
              (equal ?arm-roll nil)))
    (once (or (desig:desig-prop ?designator (:wrist-flex ?wrist-flex))
              (equal ?wrist-flex nil)))
    (once (or (desig:desig-prop ?designator (:wrist-roll ?wrist-roll))
              (equal ?wrist-roll nil)))

    (desig:designator :action ((:type :taking-pose)
                               (:pose-keyword ?pose-keyword)
                               (:head-pan ?head-pan)
                               (:head-tilt ?head-tilt)
                               (:arm-lift ?arm-lift)
                               (:arm-flex ?arm-flex)
                               (:arm-roll ?arm-roll)
                               (:wrist-flex ?wrist-flex)
                               (:wrist-roll ?wrist-roll)
                               )
                      ?resolved-action-designator))
)
